[package]
name = "devon"
description = "Uzbek NLP library"
documentation = "https://docs.rs/devon"
repository = "https://github.com/muminoff/devon.rs/"
readme = "README.md"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.44"
lazy_static = "1.4.0"
